version: '2'
#version: '3'

services:
 wild1:
  image: myimage/wildfly
  build: ./
  hostname: wild1
  volumes:
   - ./wild-docker-files/standalone-ha-1.xml:/opt/jboss/wildfly/standalone/configuration/standalone-ha.xml
   - ./volumes/wild1/deployments:/opt/jboss/wildfly/standalone/deployments
#   - ./wild-docker-files/apptest.war:/opt/jboss/wildfly/standalone/deployments/apptest.war
#   - ./wild-docker-files/apptest.war.dodeploy:/opt/jboss/wildfly/standalone/deployments/apptest.war.dodeploy
  ports:
   - "8081:8080"
   - "9991:9990"
  networks:
   wildnetwork:
      ipv4_address: 172.28.5.1
  command: /opt/jboss/wildfly/bin/standalone.sh -c standalone-ha.xml -u 230.0.0.4

 wild2:
  image: myimage/wildfly
  build: ./
  hostname: wild2
  volumes:
   - ./wild-docker-files/standalone-ha-2.xml:/opt/jboss/wildfly/standalone/configuration/standalone-ha.xml
   - ./volumes/wild2/deployments:/opt/jboss/wildfly/standalone/deployments
#   - ./wild-docker-files/apptest.war:/opt/jboss/wildfly/standalone/deployments/apptest.war
#   - ./wild-docker-files/apptest.war.dodeploy:/opt/jboss/wildfly/standalone/deployments/apptest.war.dodeploy
  ports:
   - "8082:8080"
   - "9992:9990"
  networks:
   wildnetwork:
      ipv4_address: 172.28.5.2
  command: /opt/jboss/wildfly/bin/standalone.sh -c standalone-ha.xml -u 230.0.0.4

 wild3:
  image: myimage/wildfly
  build: ./
  hostname: wild3
  volumes:
   - ./wild-docker-files/standalone-ha-3.xml:/opt/jboss/wildfly/standalone/configuration/standalone-ha.xml
   - ./volumes/wild3/deployments:/opt/jboss/wildfly/standalone/deployments
#   - ./wild-docker-files/apptest.war:/opt/jboss/wildfly/standalone/deployments/apptest.war
#   - ./wild-docker-files/apptest.war.dodeploy:/opt/jboss/wildfly/standalone/deployments/apptest.war.dodeploy
  ports:
   - "8083:8080"
   - "9993:9990"
  networks:
   wildnetwork:
      ipv4_address: 172.28.5.3
  command: /opt/jboss/wildfly/bin/standalone.sh -c standalone-ha.xml -u 230.0.0.4

 wild-balancer:
  image: jasonwyatt/nginx-loadbalancer
  ports:
   - "8091:80"
  env_file:
   - ./wild-docker-files/env.list
  environment:
   - TOMCAT_PORT=8091
  networks:
   wildnetwork:
      ipv4_address: 172.28.5.4

 console-balancer:
  image: jasonwyatt/nginx-loadbalancer
  ports:
   - "8092:80"
  environment:
   - TOMCAT_PORT=8092
   # automatically created environment variables (docker links)
   - TOMCAT_1_PORT_8080_TCP_ADDR=wild1
   - TOMCAT_2_PORT_8080_TCP_ADDR=wild2
   - TOMCAT_3_PORT_8080_TCP_ADDR=wild3
   - TOMCAT_1_PORT_9990_TCP_ADDR=wild1
   - TOMCAT_2_PORT_9990_TCP_ADDR=wild2
   - TOMCAT_3_PORT_9990_TCP_ADDR=wild3
   # special environment variables
   - TOMCAT_PATH=/console
#   - TOMCAT_REMOTE_PORT=8080
   - TOMCAT_REMOTE_PORT=9990
   - TOMCAT_REMOTE_PATH=/console
   - TOMCAT_HOSTNAME=console-balancer
  networks:
   wildnetwork:
      ipv4_address: 172.28.5.5

 nginx1:
  image: nginx
  volumes:
    - ./nginx1/conf.d:/etc/nginx/conf.d
  ports:
    - "8095:80"
  environment:
    - NGINX_HOST=nginx1
    - NGINX_PORT=80
  networks:
   wildnetwork:

 nginx2:
  image: nginx
  volumes:
    - ./nginx2/conf.d:/etc/nginx/conf.d
  ports:
    - "8096:80"
  environment:
    - NGINX_HOST=nginx1
    - NGINX_PORT=80
  networks:
   wildnetwork:

 haproxy1:
  image: haproxy:1.7
  volumes:
    - ./haproxy1/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    - ./haproxy1/conf.d:/usr/local/etc/haproxy/conf.d
  ports:
    - "8097:80"
  networks:
   wildnetwork:
#   command: "haproxy -c -f /usr/local/etc/haproxy/haproxy.cfg"
#   entrypoint: bash -c "haproxy -f /usr/local/etc/haproxy/haproxy.cfg"
#   stdin_open: true
#   tty: true
#   entrypoint: "/bin/bash"
#   command: "-c /bin/bash"



networks:
 wildnetwork:
#  driver: overlay
  driver: bridge
  ipam:
   config:
    - subnet: 172.28.0.0/16
      gateway: 172.28.5.254
#    - ip-range: 172.28.5.0/24
